# Generated by Django 5.2.4 on 2025-07-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymclass',
            name='capacity',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
