# Generated by Django 5.2.4 on 2025-07-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_gymclass_capacity_member_is_active_member_is_vip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='check_in_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='last_visit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
