# Generated by Django 5.2.4 on 2025-07-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_member_check_in_count_member_last_visit_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membership_type',
            field=models.CharField(default='Basic', max_length=20),
        ),
    ]
