# Generated by Django 5.2.4 on 2025-07-12 14:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_running', models.BooleanField(default=False)),
                ('is_deployed', models.BooleanField(default=False)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('edge_type', models.CharField(default='default', max_length=50)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='flow.flow')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('config', models.JSONField(default=dict)),
                ('connector', models.CharField(max_length=100)),
                ('connector_options', models.JSONField(default=list)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='flow.flow')),
            ],
        ),
    ]
