# Generated by Django 5.2.4 on 2025-07-12 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_node1_subnode_subnodeparameter_delete_node'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Node1',
            new_name='Node',
        ),
    ]
