# Generated by Django 5.2.4 on 2025-07-12 19:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_rename_node1_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='flow.flow'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subnode',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
